import React, { useState } from 'react';
import { FoodAnalysis, RiskLevel, MealType } from '../types';
import { AlertTriangle, CheckCircle, Info, Coffee, Sun, Moon, Edit2, ShieldAlert, Wheat, Stethoscope, Scale } from 'lucide-react';

interface Props {
  data: FoodAnalysis;
  onUpdateLog?: (timestamp: string, updatedLog: FoodAnalysis) => void;
}

const AnalysisResultCard: React.FC<Props> = ({ data, onUpdateLog }) => {
  const [isEditing, setIsEditing] = useState(false);

  const getRiskColor = (level: RiskLevel) => {
    switch (level) {
      case RiskLevel.DANGEROUS: return 'bg-red-50 border-red-200 text-red-800';
      case RiskLevel.MODERATE: return 'bg-yellow-50 border-yellow-200 text-yellow-800';
      case RiskLevel.SAFE: return 'bg-green-50 border-green-200 text-green-800';
      default: return 'bg-gray-50 border-gray-200 text-gray-800';
    }
  };

  const getRiskLabel = (level: RiskLevel) => {
    switch (level) {
      case RiskLevel.DANGEROUS: return '紅燈 - 危險';
      case RiskLevel.MODERATE: return '黃燈 - 注意';
      case RiskLevel.SAFE: return '綠燈 - 安全';
      default: return '未知';
    }
  };

  const getMealIcon = (type: string) => {
    switch (type) {
      case '早餐': return <Sun className="w-4 h-4" />;
      case '午餐': return <Sun className="w-4 h-4" />;
      case '晚餐': return <Moon className="w-4 h-4" />;
      default: return <Coffee className="w-4 h-4" />;
    }
  };

  const handleMealTypeChange = (newType: MealType) => {
    if (onUpdateLog) {
      onUpdateLog(data.timestamp, { ...data, mealType: newType });
    }
    setIsEditing(false);
  };

  // Check if the advice contains the specific warning keyword generated by AI
  const isCriticalWarning = data.healthAdvice.includes("嚴重警告") || data.healthAdvice.includes("違反飲食禁忌");

  const dateObj = new Date(data.timestamp);
  const timeString = !isNaN(dateObj.getTime()) 
    ? dateObj.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})
    : '--:--';

  return (
    <div className="w-full bg-white rounded-xl shadow-lg overflow-hidden border border-gray-100 animate-fade-in-up">
      <div className={`p-4 border-l-4 ${data.riskLevel === RiskLevel.DANGEROUS ? 'border-l-red-500' : data.riskLevel === RiskLevel.MODERATE ? 'border-l-yellow-500' : 'border-l-green-500'}`}>
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-1 relative">
              {isEditing && onUpdateLog ? (
                <div className="absolute top-0 left-0 bg-white border border-gray-200 shadow-lg rounded-lg p-1 z-10 flex flex-col gap-1 min-w-[100px]">
                   {(['早餐', '午餐', '晚餐', '點心/飲料'] as MealType[]).map(type => (
                     <button 
                       key={type}
                       onClick={() => handleMealTypeChange(type)}
                       className={`text-left px-2 py-1 text-xs rounded hover:bg-gray-100 ${data.mealType === type ? 'font-bold text-indigo-600' : 'text-gray-600'}`}
                     >
                       {type}
                     </button>
                   ))}
                </div>
              ) : (
                <button 
                  onClick={() => setIsEditing(true)}
                  disabled={!onUpdateLog}
                  className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-semibold bg-gray-100 text-gray-600 ${onUpdateLog ? 'hover:bg-gray-200 cursor-pointer' : ''}`}
                >
                  {getMealIcon(data.mealType)}
                  {data.mealType}
                  {onUpdateLog && <Edit2 className="w-3 h-3 opacity-50" />}
                </button>
              )}
              <span className="text-xs text-gray-400">{timeString}</span>
            </div>
            <h3 className="text-xl font-bold text-gray-900">{data.foodName}</h3>
            {data.diagnosis && (
                <div className="mt-1 flex items-center gap-1.5 text-sm font-medium text-slate-600">
                    <Stethoscope className="w-3.5 h-3.5 text-indigo-500" />
                    <span>{data.diagnosis}</span>
                </div>
            )}
          </div>
          
          {/* Traffic Light Visual */}
          <div className="flex flex-col items-end gap-1">
             <div className="flex gap-1.5 bg-gray-800 p-1.5 rounded-full shadow-inner">
                <div className={`w-3 h-3 rounded-full transition-all duration-500 ${data.riskLevel === RiskLevel.DANGEROUS ? 'bg-red-500 shadow-[0_0_8px_2px_rgba(239,68,68,0.6)] scale-110' : 'bg-red-900 opacity-40'}`} />
                <div className={`w-3 h-3 rounded-full transition-all duration-500 ${data.riskLevel === RiskLevel.MODERATE ? 'bg-yellow-400 shadow-[0_0_8px_2px_rgba(250,204,21,0.6)] scale-110' : 'bg-yellow-900 opacity-40'}`} />
                <div className={`w-3 h-3 rounded-full transition-all duration-500 ${data.riskLevel === RiskLevel.SAFE ? 'bg-green-500 shadow-[0_0_8px_2px_rgba(34,197,94,0.6)] scale-110' : 'bg-green-900 opacity-40'}`} />
             </div>
             <span className={`text-xs font-bold ${
                data.riskLevel === RiskLevel.DANGEROUS ? 'text-red-600' :
                data.riskLevel === RiskLevel.MODERATE ? 'text-yellow-600' :
                'text-green-600'
             }`}>
                {getRiskLabel(data.riskLevel)}
             </span>
          </div>
        </div>
      </div>

      <div className="p-4 grid grid-cols-2 gap-4 bg-gray-50">
        <div className="bg-white p-3 rounded-lg shadow-sm">
          <p className="text-xs text-gray-500 uppercase">熱量 (估算)</p>
          <div className="flex items-baseline gap-2">
             <p className="text-2xl font-bold text-indigo-600">{data.calories} <span className="text-sm font-normal text-gray-400">kcal</span></p>
             {data.estimatedWeight && (
                <span className="flex items-center gap-1 text-[10px] bg-indigo-50 text-indigo-600 px-1.5 py-0.5 rounded font-bold border border-indigo-100">
                   <Scale className="w-3 h-3"/> {data.estimatedWeight}
                </span>
             )}
          </div>
          
          {/* Ingredients Display */}
          {data.ingredients && data.ingredients.length > 0 && (
             <div className="mt-3 pt-3 border-t border-gray-100">
               <p className="text-[10px] text-gray-500 uppercase mb-2 flex items-center gap-1 font-bold"><Wheat className="w-3 h-3"/> 主要食材與其它成份</p>
               <div className="flex flex-wrap gap-1.5">
                 {data.ingredients.map((ing, i) => (
                   <span key={i} className="text-[11px] px-2 py-1 bg-gray-100 text-gray-700 rounded-md border border-gray-200">{ing}</span>
                 ))}
               </div>
             </div>
          )}
        </div>
        <div className="bg-white p-3 rounded-lg shadow-sm flex flex-col justify-center">
            <p className="text-[10px] text-gray-400 uppercase mb-1">營養成份</p>
            {data.nutrients.map((n, idx) => (
                <div key={idx} className="flex justify-between text-sm py-1 border-b border-gray-100 last:border-0">
                    <span className="text-gray-600">{n.name}</span>
                    <span className="font-medium text-gray-900">{n.amount}{n.unit}</span>
                </div>
            ))}
        </div>
      </div>

      <div className={`p-4 border-t ${getRiskColor(data.riskLevel)}`}>
        <div className="flex items-center justify-between mb-2">
            <p className="font-semibold flex items-center gap-2">
               AI 健康建議：
            </p>
            {isCriticalWarning && (
                <span className="flex items-center gap-1 text-[10px] bg-red-600 text-white px-2 py-1 rounded-full animate-pulse font-bold tracking-wider shadow-sm">
                   <ShieldAlert className="w-3 h-3" />
                   CRITICAL WARNING
                </span>
            )}
        </div>
        
        {isCriticalWarning ? (
            <div className="relative overflow-hidden bg-red-100 border-l-4 border-red-600 p-4 rounded-r-lg shadow-inner">
               <div className="absolute top-0 right-0 -mt-2 -mr-2 opacity-10">
                  <ShieldAlert className="w-24 h-24 text-red-900" />
               </div>
               <p className="relative z-10 text-sm font-bold text-red-900 leading-relaxed">
                 {data.healthAdvice}
               </p>
            </div>
        ) : (
             <p className="text-sm opacity-90 leading-relaxed text-justify">
               {data.healthAdvice}
             </p>
        )}
      </div>
    </div>
  );
};

export default AnalysisResultCard;